# Generated by Django 3.2.6 on 2021-08-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre_type',
            field=models.CharField(blank=True, choices=[('Classical', 'Classical')], max_length=10),
        ),
    ]
