# Generated by Django 3.2.6 on 2021-08-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_album_genre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre_type',
            field=models.CharField(blank=True, choices=[('Jazz', 'Jazz')], max_length=10),
        ),
    ]
