# Generated by Django 3.2.6 on 2021-08-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_album_genre_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('event_name', models.CharField(default='Workshop', max_length=100, unique=True)),
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
