# Generated by Django 3.2.6 on 2021-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0, null=True)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
